2022-12-03 20:43:19,434 INFO An INFO
2022-12-03 20:43:19,434 WARNING A WARNING
2022-12-03 20:43:19,435 ERROR An ERROR
2022-12-03 20:43:19,435 CRITICAL A message of CRITICAL severity
2022-12-03 20:43:23,282 ERROR Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-12-03 20:43:23,285 ERROR Exception traceback:
Traceback (most recent call last):
  File "C:\Users\HOME\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\HOME\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\util.py", line 118, in raise_exceptions
    raise self.exception_info
  File "C:\Users\HOME\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\util.py", line 100, in run
    task(*args, **kwargs)
  File "C:\Users\HOME\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\HOME\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\HOME\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\HOME\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\HOME\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

